// <auto-generated />
using System;
using Demo1.App_Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo1.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo1.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "A sedan is a passenger car in a three-box configuration with separate compartments for engine, passenger, and cargo.",
                            Name = "Sedan"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "A sport utility vehicle (SUV) is a versatile vehicle that combines elements of road-going passenger cars with features from off-road vehicles.",
                            Name = "SUV"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "A truck is a motor vehicle designed to transport cargo. Trucks vary greatly in size, power, and configuration.",
                            Name = "Truck"
                        });
                });

            modelBuilder.Entity("Demo1.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("DriverLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerId");

                    b.HasIndex("DriverLicenseNumber")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            DriverLicenseNumber = "D1234567",
                            Email = "ahmed.hassan@example.com",
                            FullName = "Ahmed Hassan",
                            Phone = "1234567890"
                        },
                        new
                        {
                            CustomerId = 2,
                            DriverLicenseNumber = "D7654321",
                            Email = "mona.adel@example.com",
                            FullName = "Mona Adel",
                            Phone = "0987654321"
                        },
                        new
                        {
                            CustomerId = 3,
                            DriverLicenseNumber = "D9876543",
                            Email = "omar.khaled@example.com",
                            FullName = "Omar Khaled",
                            Phone = "01010000003"
                        });
                });

            modelBuilder.Entity("Demo1.Models.CustomerProfile", b =>
                {
                    b.Property<int>("CustomerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerProfileId"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerProfileId");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("CustomerProfiles");

                    b.HasData(
                        new
                        {
                            CustomerProfileId = 1,
                            Adress = "123 Main St, Cityville",
                            CustomerId = 1,
                            DateOfBirth = new DateTime(1990, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CustomerProfileId = 2,
                            Adress = "456 Elm St, Townsville",
                            CustomerId = 2,
                            DateOfBirth = new DateTime(1985, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CustomerProfileId = 3,
                            Adress = "789 Oak St, Villageville",
                            CustomerId = 3,
                            DateOfBirth = new DateTime(1995, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Demo1.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Email = "mostafa@gmail.com",
                            FullName = "Mostafa Nabil",
                            HireDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01129344393",
                            Position = "sales manager"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Email = "Aya@gmail.com",
                            FullName = "Ahmed Abdullah",
                            HireDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01029393399",
                            Position = "Sales cosultat"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Email = "Hassan@gmail.com",
                            FullName = "Hassan Ali",
                            HireDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01029393399",
                            Position = "sales cosulatle"
                        });
                });

            modelBuilder.Entity("Demo1.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SalePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("SaleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleId = 1,
                            CustomerId = 1,
                            EmployeeId = 1,
                            Notes = "First sale",
                            PaymentMethod = "Credit Card",
                            SaleDate = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalePrice = 25000m,
                            VehicleId = 1
                        },
                        new
                        {
                            SaleId = 2,
                            CustomerId = 2,
                            EmployeeId = 2,
                            Notes = "Second sale",
                            PaymentMethod = "Cash",
                            SaleDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalePrice = 20000m,
                            VehicleId = 2
                        },
                        new
                        {
                            SaleId = 3,
                            CustomerId = 3,
                            EmployeeId = 3,
                            Notes = "Third sale",
                            PaymentMethod = "Bank Transfer",
                            SaleDate = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalePrice = 35000m,
                            VehicleId = 3
                        });
                });

            modelBuilder.Entity("Demo1.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FuelType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Mileage1")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Available");

                    b.Property<string>("Transmission")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            CategoryId = 2,
                            Color = "Blue",
                            FuelType = "Gasoline",
                            Make = "Toyota",
                            Mileage1 = 15000,
                            Model = "Camry",
                            Price = 25000m,
                            Status = "Available",
                            Transmission = "Automatic",
                            VIN = "1HGCM82633A123456",
                            Year = 2020
                        },
                        new
                        {
                            VehicleId = 2,
                            CategoryId = 1,
                            Color = "Red",
                            FuelType = "Gasoline",
                            Make = "Honda",
                            Mileage1 = 20000,
                            Model = "Civic",
                            Price = 20000m,
                            Status = "Available",
                            Transmission = "Manual",
                            VIN = "1HGCM82633A654321",
                            Year = 2019
                        },
                        new
                        {
                            VehicleId = 3,
                            CategoryId = 2,
                            Color = "Black",
                            FuelType = "Diesel",
                            Make = "Ford",
                            Mileage1 = 10000,
                            Model = "F-150",
                            Price = 35000m,
                            Status = "Available",
                            Transmission = "Automatic",
                            VIN = "1FTFW1E50MFA12345",
                            Year = 2021
                        });
                });

            modelBuilder.Entity("Demo1.Models.CustomerProfile", b =>
                {
                    b.HasOne("Demo1.Models.Customer", "Customer")
                        .WithOne("CustomerProfile")
                        .HasForeignKey("Demo1.Models.CustomerProfile", "CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("Demo1.Models.Sale", b =>
                {
                    b.HasOne("Demo1.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Demo1.Models.Employee", "Employee")
                        .WithMany("Sales")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Demo1.Models.Vehicle", "Vehicle")
                        .WithOne("Sale")
                        .HasForeignKey("Demo1.Models.Sale", "VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Demo1.Models.Vehicle", b =>
                {
                    b.HasOne("Demo1.Models.Category", "Category")
                        .WithMany("Vehicles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Demo1.Models.Category", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Demo1.Models.Customer", b =>
                {
                    b.Navigation("CustomerProfile")
                        .IsRequired();

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Demo1.Models.Employee", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("Demo1.Models.Vehicle", b =>
                {
                    b.Navigation("Sale")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
